### ISSUE TITLE
Breaks after opening the queue

### ISSUE THREAD

**Issue by TheBluePenguin** [jsejcksn/skip-steam-discovery-queues#1]
After selecting how many queues you wish to skip, it will start the queue then stop working on the first store page.

**Comment by jsejcksn** [comment]
Hi @TheBluePenguin:

The last time I looked at this was about 4 years ago. I'd be more than a little surprised if, since that time, the DOM structure of the Steam site hasn't changed in a way that is incompatible with the functionality of this user script. If you're seeing an error in the console log it's _most likely_ due to a selector that's no longer valid.

AFAIK, Steam stopped awarding trading cards for cycling through discovery queues during seasonal events years ago (and that was the entire purpose of the script), and, because of that, I have no plans to update it.

If you'd like to fork it and try to make it work, then you can use the information in the first paragraph above as a starting point for debugging/refactoring. And if you do go down that route and get it working, and you also want to submit a PR, I'd be happy to take a look at it.

---

Edit: I just took a look, and it appears that Steam is awarding trading cards for completing discovery queue reviews again this winter.

**Comment by TheBluePenguin** [comment]
Yeah. They have always kept awarding cards. but they only do 1 card instead of the previous 3. I believe the issue is on line 188 of user.js. I am currently testing my solution but I have never worked on a browser extension before and I am having difficulties. I will update the repo if I can get it working.

**Comment by jsejcksn** [comment]
@TheBluePenguin  I just created a draft PR #2 . Does that change make it work again for you?

**Comment by TheBluePenguin** [comment]
Yes. It is fully functional now. Thank you for updating this!
